'use strict';
function allocateTargets(ms,reference){
 const targets=Object.fromEntries(ms.map(m=>[m.code,reference.population2025[m.code]]));
 if(Object.values(targets).some(n=>!Number.isSafeInteger(n)||n<=0)||Object.values(targets).reduce((a,b)=>a+b,0)!==reference.target)throw Error('Los totales de alcaldía 2025 no concilian con CDMX.');
 return targets;
}
function scaledMunicipality(m){if(!estimated())return {...m,sampleN:m.n};const factor=targets[m.code]/m.n;return {...m,sampleN:m.n,n:targets[m.code],sex:m.sex.map(n=>n*factor),nat:m.nat.map(n=>n*factor),birth:m.birth.map(n=>n*factor),origins:Object.fromEntries(Object.entries(m.origins).map(([k,n])=>[k,n*factor]))};}
function chooseMunicipality(code){$('municipality').value=code;expanded=false;render();}
function mapValue(m){return ({outside:m.birth[1]+m.birth[2],abroad:m.birth[2],mexico:m.birth[1],cdmx:m.birth[0]})[$('map-metric').value]/m.n;}
function renderExplorer(rows,total){const title=rows.length===16?'Ciudad de México':rows[0].name;
 $('basis-note').textContent=estimated()?'Estimación de composición: aplica los porcentajes de la muestra a los totales 2025 proporcionados para cada alcaldía. No sustituye los factores oficiales de la encuesta.':'Conteos sin expansión. Los porcentajes describen los registros disponibles, no una estimación ponderada de la población.';
 $('scale').options[1].textContent=estimated()?'Personas estimadas':'Número de registros';
 $('metrics').innerHTML=[['Nacidos en CDMX',total.birth[0]],['Nacidos fuera de CDMX',total.birth[1]+total.birth[2]],['Otra entidad de México',total.birth[1]],['Nacidos en el extranjero',total.birth[2]]].map(([l,n])=>`<div class="metric"><span>${l}</span><strong>${pct(n,total.n)}</strong><small>${count(n)} ${unit()}</small></div>`).join('');
 $('headline-title').textContent=title+' · ¿Cuántos nacieron fuera?';$('origin-basis').textContent=estimated()?'Ajustada a totales 2025':'Muestra sin expandir';const outside=total.birth[1]+total.birth[2];
 $('origin-split').innerHTML=`<div class="split-head"><div><span>Nacidos en CDMX</span><strong>${pct(total.birth[0],total.n)}</strong></div><div><span>Nacidos fuera de CDMX</span><strong>${pct(outside,total.n)}</strong></div></div><div class="split-bar" role="img" aria-label="Nacidos en CDMX ${pct(total.birth[0],total.n)}, fuera ${pct(outside,total.n)}, no especificado ${pct(total.birth[3],total.n)}">${[total.birth[0],outside,total.birth[3]].map((n,i)=>`<span style="width:${100*n/total.n}%;background:${['#087f8c','#be6d17','#8b95a5'][i]}"></span>`).join('')}</div><div class="split-bottom"><span>Otra entidad: <strong>${pct(total.birth[1],total.n)}</strong></span><span>Extranjero: <strong>${pct(total.birth[2],total.n)}</strong></span><span>No especificado: <strong>${pct(total.birth[3],total.n)}</strong> (${count(total.birth[3])})</span></div>`;
 renderMap(total,title);
}
function renderMap(total,title){const values=municipalities.map(mapValue),lo=Math.min(...values),hi=Math.max(...values),chosen=$('municipality').value;
 const label=$('map-metric').selectedOptions[0].textContent;
 $('map').innerHTML=`<svg viewBox="0 0 ${G.width} ${G.height}" aria-label="${esc(label)} por alcaldía"><text x="545" y="35" class="north">N ↑</text>${G.features.map(f=>{const m=municipalities.find(m=>m.code===f.code),v=mapValue(m),t=(v-lo)/(hi-lo||1),fill=`rgb(${Math.round(217-207*t)},${Math.round(237-149*t)},${Math.round(240-127*t)})`;return `<path d="${f.path}" fill="${fill}" fill-rule="evenodd" class="borough ${chosen===f.code?'selected':''}" data-code="${f.code}" role="button" tabindex="0" aria-pressed="${chosen===f.code}" aria-label="${esc(m.name)}: ${pct(v,1)} ${esc(label.toLowerCase())}"><title>${esc(m.name)} · ${pct(v,1)} ${esc(label.toLowerCase())}</title></path><text x="${f.label[0]}" y="${f.label[1]}" class="map-label">${f.code.padStart(2,'0')}</text>`}).join('')}</svg>`;
 $('map').querySelectorAll('[data-code]').forEach(p=>{p.addEventListener('click',()=>chooseMunicipality(p.dataset.code));p.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();const code=p.dataset.code;chooseMunicipality(code);$('map').querySelector(`[data-code="${code}"]`)?.focus();}});});
 $('map-min').textContent=pct(lo,1);$('map-max').textContent=pct(hi,1);
 $('selected-detail').innerHTML=`<p class="eyebrow">SELECCIÓN ACTUAL</p><h3>${esc(title)}</h3><p class="selected-pop">${count(total.n)} <span>${unit()}</span></p><div class="detail-pair"><span>Nacidos fuera de CDMX</span><strong>${pct(total.birth[1]+total.birth[2],total.n)}</strong><small>${count(total.birth[1]+total.birth[2])} ${unit()}</small></div><div class="detail-pair"><span>Nacidos en el extranjero</span><strong>${pct(total.birth[2],total.n)}</strong><small>${count(total.birth[2])} ${unit()}</small></div><div class="detail-pair"><span>Nacionalidad no mexicana</span><strong>${pct(total.nat[1],total.n)}</strong><small>${count(total.nat[1])} ${unit()}</small></div><p class="footnote">Basado en ${fmt(total.sampleN)} registros. Todas las gráficas de origen se actualizan con esta selección.</p>`;
 $('map-list').innerHTML=municipalities.map(m=>`<button data-mun="${m.code}" class="${chosen===m.code?'active':''}" aria-pressed="${chosen===m.code}"><span>${m.code.padStart(2,'0')} · ${esc(m.name)}</span><strong>${pct(mapValue(m),1)}</strong></button>`).join('');
 $('map-list').querySelectorAll('[data-mun]').forEach(b=>b.addEventListener('click',()=>chooseMunicipality(b.dataset.mun)));
}
function initializeReference(){
 $('reset-map').addEventListener('click',()=>chooseMunicipality('all'));
 $('age-chart').innerHTML=R.age.map(a=>`<div class="origin-row"><div class="origin-label"><span>${a.label}</span><span>${fmt(a.n)} · ${pct(a.n,R.target)}</span></div><div class="origin-track"><div class="origin-fill" style="width:${100*a.n/R.target}%;background:#5474d3"></div></div></div>`).join('')+'<p class="footnote">Porcentaje sobre 9,165,819. Las cuatro edades suman el total; “no especificado” aparece como NA en la imagen.</p>';
 $('methodology').innerHTML=`<p><strong>Estimación propia, no estimador oficial.</strong> El total objetivo es ${fmt(R.target)} habitantes en viviendas particulares habitadas, transcrito de la imagen proporcionada. Los totales por alcaldía se transcriben directamente de la columna 2025 de la nueva imagen y suman ${fmt(R.target)}. La columna 2020 se conserva solo como referencia; no interviene en el cálculo.</p><ol><li>Población de cada alcaldía = valor 2025 proporcionado en la imagen. No se redistribuye ni se reescala este valor.</li><li>Factor de ajuste de cada alcaldía = población 2025 / número de registros de esa alcaldía.</li><li>Personas estimadas de un grupo = registros del grupo × factor de su alcaldía. La cifra de CDMX es la suma de las 16 estimaciones; no es el porcentaje de la muestra completa multiplicado por el total.</li></ol><p><strong>Supuestos:</strong> se supone que la muestra representa la composición por origen dentro de cada alcaldía. No se conocen probabilidades de selección, no respuesta ni diseño muestral; no se calculan márgenes de error. El universo de la imagen es viviendas particulares habitadas y no se ha confirmado que coincida exactamente con el de la tabla 2025 y la base. Las proporciones por sexo y edad de la imagen no se usan para calibrar los registros.</p><p>Los porcentajes por alcaldía no cambian con el factor constante. El porcentaje de toda CDMX sí cambia al ponderar las alcaldías. Las cifras con ≈ se redondean al entero más cercano y los subtotales mostrados pueden diferir por redondeo.</p><p><strong>Origen:</strong> ENT_PAIS_NAC indica nacimiento, no residencia previa ni migración reciente. 9 = CDMX; otras claves 1–32 = otra entidad mexicana; claves catalogadas 100–536 = extranjero. 997, 998 y 999 permanecen como no especificados. Todos están en el denominador.</p><p><strong>Fuente de registros:</strong> ${esc(D.source)}, hojas database, entidad y alcaldia; ${fmt(D.total)} filas. Se cuenta cada fila una vez; NUMPER no es un factor. No se aplican factores oficiales porque no están disponibles en este archivo. Claves sin catálogo: ${D.audit.unmatchedMunicipalities} de alcaldía y ${D.audit.unmatchedOrigins} de origen.</p><p><strong>Sexo:</strong> se conserva 1 = mujeres y 3 = hombres, según la indicación inicial. Su distribución no está conciliada con los porcentajes de la imagen y requiere confirmar el diccionario. La referencia de edad y sexo de la imagen se presenta separadamente.</p><p><strong>Cartografía:</strong> <a href="${G.source}">INEGI, Marco Geoestadístico, diciembre de 2025</a>. Se usan únicamente sus polígonos; los datos de población del servicio cartográfico no sustituyen los insumos proporcionados. El mapa funciona sin conexión. Sus colores representan porcentajes con una escala entre el mínimo y el máximo de las 16 alcaldías.</p>`;
 $('weights-table').innerHTML='<caption>Totales proporcionados 2025 y factores de ajuste de la muestra</caption><thead><tr><th>Alcaldía</th><th>Referencia 2020</th><th>Población 2025</th><th>Registros</th><th>Factor</th></tr></thead><tbody>'+municipalities.map(m=>`<tr><th scope="row">${esc(m.name)}</th><td>${fmt(R.prior[m.code])}</td><td>${fmt(targets[m.code])}</td><td>${fmt(m.n)}</td><td>${(targets[m.code]/m.n).toFixed(4)}</td></tr>`).join('')+`<tr><th>Total</th><td>${fmt(R.priorTotal)}</td><td>${fmt(R.target)}</td><td>${fmt(D.total)}</td><td>Varía por alcaldía</td></tr></tbody>`;
}
