'use strict';
const T=window.TABULADOS,G=window.MAP_DATA,$=id=>document.getElementById(id);
const nf=new Intl.NumberFormat('es-MX',{maximumFractionDigits:0}),precise=new Intl.NumberFormat('es-MX',{maximumFractionDigits:6});
const fmt=n=>n==null?'Sin dato':nf.format(n),raw=n=>typeof n==='number'?precise.format(n):String(n??'Sin dato');
const pct=n=>n==null?'Sin dato':n.toFixed(2)+'%',esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const palette=['#087f8c','#5474d3','#a66406','#ab588d','#8b95a5','#52677e','#b94d42'];
const topics={city:[['birth','Lugar de nacimiento'],['residence','Residencia hace 5 años'],['population','Población y sexo'],['education','Educación'],['income','Ingresos monetarios'],['housing','Vivienda'],['disability','Discapacidad']],national:[['population','Población por entidad'],['education','Educación'],['income','Ingresos monetarios'],['disability','Discapacidad'],['health','Salud']]};
const names={'2':'Azcapotzalco','3':'Coyoacán','4':'Cuajimalpa de Morelos','5':'Gustavo A. Madero','6':'Iztacalco','7':'Iztapalapa','8':'La Magdalena Contreras','9':'Milpa Alta','10':'Álvaro Obregón','11':'Tláhuac','12':'Tlalpan','13':'Xochimilco','14':'Benito Juárez','15':'Cuauhtémoc','16':'Miguel Hidalgo','17':'Venustiano Carranza'};
const normalize=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace('gustvo','gustavo').trim();
let scope='city',topic='birth',area='all';
function table(id){return T.tables[id]}
function record(id,key){return table(id).rows.find(r=>r.key===key)}
function displayName(r){return r.label.replace(/^\d{9}\s*/,'').split(',')[0].replace('Gustvo','Gustavo')}
function source(id){const t=table(id);return `<p class="source-line">Fuente: ${esc(T.source)} · hoja <strong>${esc(t.sheet)}</strong>.</p>`}
function noteMarkup(value){return esc(value).replace(/([1-4])\//g,'<sup>$1</sup>').replace(/([a-zA-Záéíóúñ)])([2-4])$/g,'$1<sup>$2</sup>')}
function fullTable(id){const t=table(id);return `<details class="source-tables"><summary>Ver tabulado completo · ${esc(t.sheet)}</summary><div class="table-wrap"><table><caption>Valores del archivo; hasta seis decimales. Las fracciones originales no se convierten en esta tabla.</caption><thead><tr>${t.headers.map(h=>`<th scope="col">${noteMarkup(h)}</th>`).join('')}</tr></thead><tbody>${t.rows.map(r=>`<tr><th scope="row">${noteMarkup(r.label)}</th>${r.values.map(v=>`<td>${esc(raw(v))}</td>`).join('')}</tr>`).join('')}</tbody></table></div>${t.notes.map(n=>`<p class="footnote">${noteMarkup(n)}</p>`).join('')}</details>`}
function cards(items){$('metrics').innerHTML=items.map(([label,value,note])=>`<div class="metric"><span>${esc(label)}</span><strong>${esc(value)}</strong><small>${esc(note||'')}</small></div>`).join('')}
function bars(rows,idx=0,color='#087f8c',links=false){const max=Math.max(...rows.map(r=>r.values[idx]||0),1);return rows.map(r=>`<div class="origin-row"><div class="chart-label">${links?`<button data-area="${esc(r.key)}">${esc(displayName(r))}</button>`:`<span>${esc(displayName(r))}</span>`}<span>${fmt(r.values[idx])}</span></div><div class="origin-track"><div class="origin-fill" style="width:${100*(r.values[idx]||0)/max}%;background:${color}"></div></div></div>`).join('')}
function pairBars(rows,has2025=true){const max=Math.max(...rows.flatMap(r=>has2025?r.values.slice(0,2):r.values.slice(0,1)),1);return `<div class="chart-legend"><span><i class="dot bar-2020"></i>2020</span>${has2025?'<span><i class="dot bar-2025"></i>2025</span>':''}</div>`+rows.map(r=>`<div class="compare-item"><div class="chart-label"><span>${esc(displayName(r))}</span><span>${fmt(r.values[0])}${has2025?' → '+fmt(r.values[1]):''}</span></div><div class="two-bars"><div class="origin-track"><div class="origin-fill bar-2020" style="width:${100*r.values[0]/max}%"></div></div>${has2025?`<div class="origin-track"><div class="origin-fill bar-2025" style="width:${100*r.values[1]/max}%"></div></div>`:''}</div></div>`).join('')}
function distribution(labels,values){return `<div class="official-stack" role="img" aria-label="${esc(labels.map((l,i)=>l+': '+pct(values[i])).join(', '))}">${values.map((v,i)=>`<span title="${esc(labels[i])}: ${pct(v)}" style="width:${v}%;background:${palette[i]}"></span>`).join('')}</div><div class="distribution-list">${labels.map((l,i)=>`<div class="distribution-item"><i class="dot" style="background:${palette[i]}"></i><span>${esc(l)}</span><strong>${pct(values[i])}</strong></div>`).join('')}</div>`}
function populationRows(){return table(scope==='city'?'populationCity':'populationNational').rows.slice(1)}
function setOptions(){const allCity=table('populationCity').rows.slice(1).sort((a,b)=>a.label.localeCompare(b.label,'es'));$('area-caption').textContent=scope==='city'?'Alcaldía':'Entidad federativa';$('topic').innerHTML=topics[scope].map(([v,l])=>`<option value="${v}">${l}</option>`).join('');$('topic').value=topic;$('area').innerHTML='<option value="all">'+(scope==='city'?'Todas las alcaldías':'Todas las entidades')+'</option>'+(scope==='city'?allCity:populationRows().sort((a,b)=>a.label.localeCompare(b.label,'es'))).map(r=>`<option value="${esc(r.key)}">${esc(displayName(r))}</option>`).join('');$('area').value=area;}
function mapMarkup(valueFor,keyLabel){const all=G.features.map(f=>({f,name:names[f.code],key:normalize(names[f.code]),value:valueFor(normalize(names[f.code]))}));const present=all.filter(x=>x.value!=null),lo=Math.min(...present.map(x=>x.value)),hi=Math.max(...present.map(x=>x.value));return `<div class="map-layout"><div><div id="map"><svg viewBox="0 0 ${G.width} ${G.height}" aria-label="Mapa de alcaldías: ${esc(keyLabel)}"><text x="545" y="35" class="north">N ↑</text>${all.map(({f,name,key,value})=>{const t=value==null?0:(value-lo)/(hi-lo||1),fill=value==null?'#d9dce2':`rgb(${Math.round(217-207*t)},${Math.round(237-149*t)},${Math.round(240-127*t)})`;return `<path d="${f.path}" fill="${fill}" fill-rule="evenodd" class="borough ${area===key?'selected':''}" tabindex="0" role="button" aria-pressed="${area===key}" data-area="${esc(key)}" aria-label="${esc(name)}: ${value==null?'sin dato':keyLabel==='Población'?fmt(value):pct(value)}"><title>${esc(name)} · ${value==null?'Sin dato':keyLabel==='Población'?fmt(value):pct(value)}</title></path><text class="map-label" x="${f.label[0]}" y="${f.label[1]}">${f.code.padStart(2,'0')}</text>`}).join('')}</svg></div><div class="map-key"><span>${keyLabel==='Población'?fmt(lo):pct(lo)}</span><div class="gradient"></div><span>${keyLabel==='Población'?fmt(hi):pct(hi)}</span></div><p class="footnote">${esc(keyLabel)} · gris: sin dato. Clic o Tab y Enter para seleccionar.</p><p class="footnote">Límites de alcaldías: INEGI. Los indicadores de origen y residencia corresponden a la localidad incluida, no a toda la alcaldía.</p></div><div><button class="secondary all-regions" data-area="all">Ver todas las alcaldías</button><div id="map-detail"></div><div class="map-list">${all.sort((a,b)=>a.name.localeCompare(b.name,'es')).map(x=>`<button data-area="${esc(x.key)}" class="${area===x.key?'active':''}"><span>${x.f.code.padStart(2,'0')} · ${esc(x.name)}</span><strong>${x.value==null?'Sin dato':keyLabel==='Población'?fmt(x.value):pct(x.value)}</strong></button>`).join('')}</div></div></div>`}
function locationSummary(id){const t=table(id),rows=area==='all'?t.rows:t.rows.filter(r=>r.key===area);if(!rows.length)return null;const n=rows.reduce((s,r)=>s+r.values[1],0),values=t.headers.slice(3).map((_,i)=>rows.reduce((s,r)=>s+r.values[1]*r.values[i+2],0)/n);return {rows,n,values};}
function locationView(){const id=topic==='birth'?'birth':'residence',birth=id==='birth',s=locationSummary(id),labels=birth?['En CDMX','Otra entidad','Estados Unidos','Otro país¹','No especificado²']:['Misma demarcación','Otra demarcación de CDMX','Demarcación no especificada','Otra entidad','Estados Unidos','Otro país¹','No especificado²'];
 const metric=$('map-metric').value;
 const getValue=key=>{const r=record(id,key);if(!r)return null;const v=r.values.slice(2);return birth?(metric==='local'?v[0]:metric==='foreign'?v[2]+v[3]:v[1]+v[2]+v[3]):v[3]+v[4]+v[5]};
 const metricLabel=birth?(metric==='local'?'Nacidos en CDMX':metric==='foreign'?'Nacidos en el extranjero':'Nacidos fuera de CDMX'):'Residían fuera de CDMX en 2020';
 $('coverage').textContent=(birth?'Lugar de nacimiento. ':'Residencia en octubre de 2020; población de 5 años y más. ')+(area==='all'?'Resumen de las 15 localidades incluidas, sin Milpa Alta. No es el total de CDMX. Los porcentajes del resumen se ponderan con la población de cada fila.':'Dato de la localidad del mismo nombre, en el tabulado de localidades de 50,000 habitantes o más.');
 if(s){const v=s.values,out=birth?v[1]+v[2]+v[3]:v[3]+v[4]+v[5],ab=birth?v[2]+v[3]:v[4]+v[5];cards([['Población cubierta',fmt(s.n),birth?'Universo del tabulado':'Personas de 5 años y más'],[birth?'Nacidos fuera de CDMX':'Residían fuera de CDMX',pct(out),'Suma de categorías del tabulado'],[birth?'Nacidos en el extranjero':'Residían en el extranjero',pct(ab),'Estados Unidos + otro país'],['No especificado²',pct(v[v.length-1]),'Conservado en el denominador']]);}else cards([['Localidad seleccionada','Sin dato','Milpa Alta no está incluida'],['Lugar de nacimiento','Sin dato','No se imputa'],['Residencia en 2020','Sin dato','No se imputa'],['Fuente','15 localidades','Cobertura del archivo']]);
 $('content').innerHTML=`<section class="panel map-panel"><div class="topic-header"><div><p class="eyebrow">CDMX / LOCALIDADES INCLUIDAS</p><h2>${birth?'Lugar de nacimiento':'Residencia hace 5 años'}</h2></div><span class="coverage-badge">Tabulado proporcionado</span></div>${mapMarkup(getValue,metricLabel)}${source(id)}${fullTable(id)}</section>`;
 $('map-detail').innerHTML=s?`<h3>${area==='all'?'15 localidades incluidas':esc(displayName(s.rows[0]))}</h3><p class="detail-topic">${area==='all'?'Resumen calculado a partir de los tabulados.':'Porcentajes publicados en la hoja.'}</p>${distribution(labels,s.values)}<p class="footnote">¹ Incluye país no especificado. ² Incluye entidad no especificada. ${birth?'Nacimiento no equivale a migración reciente.':'Un cambio entre demarcaciones de CDMX no implica haber residido fuera de la ciudad.'}</p>`:'<div class="empty"><h3>Sin dato para Milpa Alta</h3><p>Esta localidad no aparece en la hoja. Puedes consultar su población en “Población y sexo”.</p></div>';
}
function cityPopulationChange(){
 const baseline=T.populationCity2020,rows=table('populationCity').rows.map(r=>({label:displayName(r),key:r.key,values:[baseline.values[r.key],r.values[0]]})),r=rows.find(r=>r.key===(area==='all'?'total':area)),v=r.values,delta=v[1]-v[0],label=area==='all'?'Ciudad de México':r.label;
 const signed=n=>(n>0?'+':'')+fmt(n),percent=(a,b)=>(b>a?'+':'')+pct(100*(b-a)/a);
 return `<section class="panel"><h2>${esc(label)} · Cambio de población 2020–2025</h2><p class="topic-note">${fmt(v[0])} habitantes en 2020 y ${fmt(v[1])} en 2025. Cambio: <strong>${signed(delta)} habitantes (${percent(v[0],v[1])})</strong>.</p>${pairBars([{label,values:v}])}<details class="source-tables"><summary>Comparar todas las alcaldías · 2020–2025</summary><div class="table-wrap"><table><thead><tr><th scope="col">Alcaldía</th><th scope="col">2020</th><th scope="col">2025</th><th scope="col">Cambio absoluto</th><th scope="col">Cambio porcentual</th></tr></thead><tbody>${rows.map(x=>`<tr><th scope="row">${x.key==='total'?'Total CDMX':`<button data-area="${esc(x.key)}">${esc(x.label)}</button>`}</th><td>${fmt(x.values[0])}</td><td>${fmt(x.values[1])}</td><td>${signed(x.values[1]-x.values[0])}</td><td>${percent(...x.values)}</td></tr>`).join('')}</tbody></table></div></details><p class="source-line">2020: ${esc(baseline.source)} 2025: ${esc(T.source)} · hoja Poblacion Cdmx. Las filas se relacionan por nombre de alcaldía.</p></section>`;
}
function populationView(){const city=scope==='city',id=city?'populationCity':'populationNational',t=table(id),r=area==='all'?t.rows[0]:record(id,area),v=r.values;
 $('coverage').textContent=city?'Población por alcaldía y sexo según la hoja Poblacion Cdmx. Los porcentajes de mujeres y hombres se calculan con las cantidades de esta hoja.':'Población por entidad: comparación 2020–2025. Variaciones calculadas como (2025 / 2020 − 1) × 100; se conservan los campos originales en la tabla.';
 if(city){cards([['Población',fmt(v[0]),area==='all'?'Total CDMX':displayName(r)],['Mujeres',pct(100*v[1]/v[0]),fmt(v[1])+' personas'],['Hombres',pct(100*v[2]/v[0]),fmt(v[2])+' personas'],['Participación en CDMX',pct(100*v[0]/t.rows[0].values[0]),'Cociente calculado']]);$('content').innerHTML=`<section class="panel map-panel"><h2>Población por alcaldía</h2>${mapMarkup(k=>record(id,k)?.values[0]??null,'Población')}${source(id)}${fullTable(id)}</section>`;$('map-detail').innerHTML=`<h3>${area==='all'?'Ciudad de México':esc(displayName(r))}</h3>${distribution(['Mujeres','Hombres'],[100*v[1]/v[0],100*v[2]/v[0]])}<p class="footnote">Cantidades del tabulado; no se usan los códigos de sexo de los microdatos.</p>`;
 $('content').insertAdjacentHTML('beforeend',cityPopulationChange());
 }else{const delta=v[1]-v[0];cards([['Población 2025',fmt(v[1]),area==='all'?'Total nacional':displayName(r)],['Población 2020',fmt(v[0]),'Misma entidad o total'],['Cambio absoluto',(delta>0?'+':'')+fmt(delta),'2025 menos 2020'],['Cambio porcentual',(delta>0?'+':'')+pct(100*delta/v[0]),'Calculado sobre 2020']]);$('content').innerHTML=`<section class="panel"><h2>${area==='all'?'Población por entidad federativa':esc(displayName(r))}</h2><p class="unit-note">${area==='all'?'2025 · selecciona un nombre para comparar ambos años.':'Cantidades reportadas en 2020 y 2025.'}</p>${area==='all'?bars([...t.rows.slice(1)].sort((a,b)=>b.values[1]-a.values[1]),1,'#087f8c',true):pairBars([r])}${source(id)}${fullTable(id)}</section>`;}
}
function comparativeView(){const suffix=scope==='city'?'City':'National',id=topic+suffix,t=table(id),total=t.rows[0],has2025=total.values.length>1,v=total.values,year=has2025?'2025':'2020';let notes='';
 if(topic==='education')notes='Básica es un subtotal de preescolar, primaria y secundaria. La gráfica principal no vuelve a sumar esos tres niveles. Universo: población de 3 años y más (nota 1/).';
 if(topic==='income')notes='Hogares que reciben ingresos monetarios de fuentes distintas al trabajo. Cada porcentaje se calcula respecto al total de hogares y la suma puede superar 100%: un hogar puede recibir más de una fuente. Las barras muestran hogares, no pesos. En la hoja CDMX, el campo original “Estructura” usa el total nacional; se conserva en la tabla y no se interpreta como porcentaje de hogares de CDMX.';
 if(topic==='disability')notes=scope==='city'?'La hoja CDMX solo contiene 2020. Sus grupos suman 1,703,827, pero el total indicado es 1,703,791; se conservan ambos sin corregirlos.':'Cantidades por grupo de edad en 2020 y 2025. No equivalen a la prevalencia dentro de cada edad, pues la hoja no incluye esos denominadores.';
 if(topic==='health')notes='Cantidades por institución. Las categorías no se suman para reconstruir el total: pueden no ser excluyentes y la hoja no desarrolla sus notas 2–4. “No especificado” de 2025 se conserva en cero, tal como figura en el archivo.';
 $('coverage').textContent=(scope==='city'?'CDMX completa':'Total nacional')+' · '+(has2025?'2020 y 2025.':'Solo 2020.')+' Este tema no tiene desglose territorial en el archivo.'+(topic==='education'?' Población de 3 años y más.':'');
 const change=has2025?100*(v[1]/v[0]-1):null;
 cards([['Total '+year,fmt(v[has2025?1:0]),topic==='income'?'Total de hogares':'Total de esta hoja'],['Total 2020',fmt(v[0]),topic==='income'?'Total de hogares':'Universo propio del tema'],['Cambio 2020–2025',change==null?'Sin dato':pct(change),change==null?'No hay columna 2025':'Calculado desde las cantidades'],['Cobertura',scope==='city'?'CDMX':'Nacional','Sin desglose por '+(scope==='city'?'alcaldía':'entidad')]]);
 const sub=r=>/^(Preescolar|Primaria|Secundaria)/.test(r.label);const rows=t.rows.slice(1).filter(r=>topic!=='education'||!sub(r));
 $('content').innerHTML=`<section class="panel"><h2>${topics[scope].find(x=>x[0]===topic)[1]}</h2><p class="topic-note">${notes}</p><div class="plot-compact">${pairBars(rows,has2025)}</div>${topic==='education'?`<details><summary>Desglose de educación básica</summary>${pairBars(t.rows.filter(sub))}</details>`:''}${['education','income'].includes(topic)?`<div class="education-notes"><h3>Notas de ${topic==='education'?'educación':'ingresos'}</h3>${t.notes.map(n=>`<p class="footnote">${noteMarkup(n)}</p>`).join('')}<p class="source-line">${esc(t.notesSource)}</p></div>`:''}${source(id)}${fullTable(id)}</section>`;
}
function housingView(){const t=table('housingCity'),r=area==='all'?t.rows[0]:record('housingCity',area),types=table('housingType');$('coverage').textContent='Vivienda: cifras de las hojas proporcionadas. La hoja por alcaldía contiene 15 demarcaciones, sin Milpa Alta; las tipologías corresponden a CDMX completa y no cambian con el selector.';cards([['Viviendas',r?fmt(r.values[0]):'Sin dato',area==='all'?'Total de la hoja':$('area').selectedOptions[0].textContent],['Total CDMX',fmt(t.rows[0].values[0]),'Viviendas del tabulado'],['Alcaldías con dato','15 de 16','Milpa Alta no está incluida'],['Diferencia sin asignar','43,069','Total menos filas disponibles']]);$('content').innerHTML=`<section class="panel"><h2>Vivienda por alcaldía</h2><p class="topic-note">Las filas disponibles suman 2,979,488 y el total de la hoja es 3,022,557. No se asigna la diferencia a Milpa Alta ni a otra demarcación.</p>${r?bars(area==='all'?[...t.rows.slice(1)].sort((a,b)=>b.values[0]-a.values[0]):[r],0,'#087f8c',true):'<p class="empty">Sin dato para Milpa Alta.</p>'}${source('housingCity')}${fullTable('housingCity')}</section><section class="panel"><h2>Tipos de vivienda · CDMX completa</h2><p class="unit-note">Total de la hoja: ${fmt(types.rows[0].values[0])}. Las barras muestran cantidades.</p>${bars(types.rows.slice(1))}${source('housingType')}${fullTable('housingType')}</section>`;}
function render(){const geographic=(scope==='city'&&['birth','residence','population','housing'].includes(topic))||(scope==='national'&&topic==='population');$('area-label').hidden=!geographic;$('metric-label').hidden=!(scope==='city'&&topic==='birth');if(topic==='birth'||topic==='residence')locationView();else if(topic==='population')populationView();else if(topic==='housing')housingView();else comparativeView();}
function changeScope(next){scope=next;topic=scope==='city'?'birth':'population';area='all';document.querySelectorAll('[data-scope]').forEach(b=>{const active=b.dataset.scope===scope;b.setAttribute('aria-selected',active);b.tabIndex=active?0:-1});$('scope-content').setAttribute('aria-labelledby','tab-'+scope);setOptions();render();}
document.querySelectorAll('[data-scope]').forEach(b=>{b.addEventListener('click',()=>changeScope(b.dataset.scope));b.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();changeScope(e.key==='Home'?'city':e.key==='End'?'national':scope==='city'?'national':'city');$('tab-'+scope).focus();}})});
$('topic').addEventListener('change',()=>{topic=$('topic').value;area='all';$('area').value='all';render()});$('area').addEventListener('change',()=>{area=$('area').value;render()});$('map-metric').addEventListener('change',render);
$('content').addEventListener('click',e=>{const el=e.target.closest('[data-area]');if(el){area=el.dataset.area;$('area').value=area;render()}});
$('content').addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('path[data-area]')){e.preventDefault();area=e.target.dataset.area;$('area').value=area;render();$('content').querySelector(`path[data-area="${area}"]`)?.focus()}});
$('audit').innerHTML='<h3>Observaciones del archivo</h3>'+T.issues.map(x=>`<p class="audit-item"><strong>${esc(x.sheet)}:</strong> ${esc(x.message)}</p>`).join('');$('footer-source').textContent=T.source+' · 13 hojas · extracción '+T.extracted;setOptions();render();
